### PR TITLE
Allow users to submit data as query

### PR DESCRIPTION
**Pull request by JeffCave**
fix of unimplemented features (use user specified parameters)
- use specified port
- send as HTTP Form rather than JSON

### CODE REVIEW

**Comment by giowild** [comment]
Hi Jeff, thanks for your contribution, great to hear Google Oauth works fine too!

Did you try using the _tr.form_ parameter  directly and leave _tr.params_ null?  

Once specified, _tr.form_ is handled directly by request object, [in this way](https://github.com/request/request#forms). That should be sufficient to handle Google Oauth too. Can you give it a try?

**Comment by JeffCave** [comment]
That worked perfectly, but raises the question, is the intent for users to specify the data:
1. by "form"
2. by "params"
3. or by each depending on whether they want it URL encoded or JSON encoded?

The use of `params` + `asquery` was based on: https://www.smileupps.com/couch-daemon-triggerjob

**Comment by giowild** [comment]
Hi Jeff,

our intent was the 3rd. 

Thanks for linking that page. It definitely needs some updates after our last changes to triggerjob. I think it would then be better to drop the _asquery_ parameter and point the user to use _form_ instead of _params_ in case of URL encoded parameters. This sounds good for you too?

**Comment by JeffCave** [comment]
That actually clarifies a great deal. I would say this merge is incorrect given the intent. 

I've never rejected a Pull-Request... I'll have a go at withdrawing it.

**Pull request closed without merging**
